[package]
name = "cortex"
version = "0.1.0"
edition = "2021"

[dependencies]
minus = { git = "https://github.com/AMythicDev/minus", features = [
  "dynamic_output",
  "search",
] }
anyhow = { version = "1.0.86", features = ["backtrace"] }
atty = "0.2.14"
